#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ReportProjectDB")]
	public partial class RprtPrjDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReport(Report instance);
    partial void UpdateReport(Report instance);
    partial void DeleteReport(Report instance);
    #endregion
		
		public RprtPrjDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ReportProjectDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RprtPrjDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RprtPrjDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RprtPrjDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RprtPrjDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Report> Reports
		{
			get
			{
				return this.GetTable<Report>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pInsReport")]
		public int pInsReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportName", DbType="NVarChar(50)")] string reportName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportHeader", DbType="NVarChar(50)")] string reportHeader, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportQuery", DbType="NVarChar(50)")] string reportQuery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportConnectionString", DbType="NVarChar(50)")] string reportConnectionString)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportName, reportHeader, reportQuery, reportConnectionString);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pSelReport")]
		public ISingleResult<pSelReportResult> pSelReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportID", DbType="Int")] System.Nullable<int> reportID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reportID);
			return ((ISingleResult<pSelReportResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reports")]
	public partial class Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReportID;
		
		private string _ReportName;
		
		private string _ReportHeader;
		
		private string _ReportQuery;
		
		private string _ReportConnectionString;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReportIDChanging(int value);
    partial void OnReportIDChanged();
    partial void OnReportNameChanging(string value);
    partial void OnReportNameChanged();
    partial void OnReportHeaderChanging(string value);
    partial void OnReportHeaderChanged();
    partial void OnReportQueryChanging(string value);
    partial void OnReportQueryChanged();
    partial void OnReportConnectionStringChanging(string value);
    partial void OnReportConnectionStringChanged();
    #endregion
		
		public Report()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReportID
		{
			get
			{
				return this._ReportID;
			}
			set
			{
				if ((this._ReportID != value))
				{
					this.OnReportIDChanging(value);
					this.SendPropertyChanging();
					this._ReportID = value;
					this.SendPropertyChanged("ReportID");
					this.OnReportIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="NVarChar(50)")]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this.OnReportNameChanging(value);
					this.SendPropertyChanging();
					this._ReportName = value;
					this.SendPropertyChanged("ReportName");
					this.OnReportNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportHeader", DbType="NVarChar(50)")]
		public string ReportHeader
		{
			get
			{
				return this._ReportHeader;
			}
			set
			{
				if ((this._ReportHeader != value))
				{
					this.OnReportHeaderChanging(value);
					this.SendPropertyChanging();
					this._ReportHeader = value;
					this.SendPropertyChanged("ReportHeader");
					this.OnReportHeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportQuery", DbType="NVarChar(50)")]
		public string ReportQuery
		{
			get
			{
				return this._ReportQuery;
			}
			set
			{
				if ((this._ReportQuery != value))
				{
					this.OnReportQueryChanging(value);
					this.SendPropertyChanging();
					this._ReportQuery = value;
					this.SendPropertyChanged("ReportQuery");
					this.OnReportQueryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportConnectionString", DbType="NVarChar(50)")]
		public string ReportConnectionString
		{
			get
			{
				return this._ReportConnectionString;
			}
			set
			{
				if ((this._ReportConnectionString != value))
				{
					this.OnReportConnectionStringChanging(value);
					this.SendPropertyChanging();
					this._ReportConnectionString = value;
					this.SendPropertyChanged("ReportConnectionString");
					this.OnReportConnectionStringChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class pSelReportResult
	{
		
		private int _ReportID;
		
		private string _ReportName;
		
		private string _ReportHeader;
		
		private string _ReportQuery;
		
		private string _ReportConnectionString;
		
		public pSelReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportID", DbType="Int NOT NULL")]
		public int ReportID
		{
			get
			{
				return this._ReportID;
			}
			set
			{
				if ((this._ReportID != value))
				{
					this._ReportID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="NVarChar(50)")]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportHeader", DbType="NVarChar(50)")]
		public string ReportHeader
		{
			get
			{
				return this._ReportHeader;
			}
			set
			{
				if ((this._ReportHeader != value))
				{
					this._ReportHeader = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportQuery", DbType="NVarChar(50)")]
		public string ReportQuery
		{
			get
			{
				return this._ReportQuery;
			}
			set
			{
				if ((this._ReportQuery != value))
				{
					this._ReportQuery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportConnectionString", DbType="NVarChar(50)")]
		public string ReportConnectionString
		{
			get
			{
				return this._ReportConnectionString;
			}
			set
			{
				if ((this._ReportConnectionString != value))
				{
					this._ReportConnectionString = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
