//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ReportSvcSoap")]
    public interface ReportSvcSoap {
        
        // CODEGEN: Generating message contract since element name GetReportResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        FrontEnd.ServiceReference1.GetReportResponse GetReport(FrontEnd.ServiceReference1.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        System.Threading.Tasks.Task<FrontEnd.ServiceReference1.GetReportResponse> GetReportAsync(FrontEnd.ServiceReference1.GetReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReport", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.ServiceReference1.GetReportRequestBody Body;
        
        public GetReportRequest() {
        }
        
        public GetReportRequest(FrontEnd.ServiceReference1.GetReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetReportRequestBody() {
        }
        
        public GetReportRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrontEnd.ServiceReference1.GetReportResponseBody Body;
        
        public GetReportResponse() {
        }
        
        public GetReportResponse(FrontEnd.ServiceReference1.GetReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrontEnd.ServiceReference1.ArrayOfString GetReportResult;
        
        public GetReportResponseBody() {
        }
        
        public GetReportResponseBody(FrontEnd.ServiceReference1.ArrayOfString GetReportResult) {
            this.GetReportResult = GetReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportSvcSoapChannel : FrontEnd.ServiceReference1.ReportSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportSvcSoapClient : System.ServiceModel.ClientBase<FrontEnd.ServiceReference1.ReportSvcSoap>, FrontEnd.ServiceReference1.ReportSvcSoap {
        
        public ReportSvcSoapClient() {
        }
        
        public ReportSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.ServiceReference1.GetReportResponse FrontEnd.ServiceReference1.ReportSvcSoap.GetReport(FrontEnd.ServiceReference1.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public FrontEnd.ServiceReference1.ArrayOfString GetReport(int id) {
            FrontEnd.ServiceReference1.GetReportRequest inValue = new FrontEnd.ServiceReference1.GetReportRequest();
            inValue.Body = new FrontEnd.ServiceReference1.GetReportRequestBody();
            inValue.Body.id = id;
            FrontEnd.ServiceReference1.GetReportResponse retVal = ((FrontEnd.ServiceReference1.ReportSvcSoap)(this)).GetReport(inValue);
            return retVal.Body.GetReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.ServiceReference1.GetReportResponse> FrontEnd.ServiceReference1.ReportSvcSoap.GetReportAsync(FrontEnd.ServiceReference1.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.ServiceReference1.GetReportResponse> GetReportAsync(int id) {
            FrontEnd.ServiceReference1.GetReportRequest inValue = new FrontEnd.ServiceReference1.GetReportRequest();
            inValue.Body = new FrontEnd.ServiceReference1.GetReportRequestBody();
            inValue.Body.id = id;
            return ((FrontEnd.ServiceReference1.ReportSvcSoap)(this)).GetReportAsync(inValue);
        }
    }
}
